"""add output_schema and output_key to agents

Revision ID: 106c23bffdaf
Revises: 6d5d5f21bae4
Create Date: 2026-07-06 15:42:42.277377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '106c23bffdaf'
down_revision = '6d5d5f21bae4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='agent_forge')
    op.add_column('agents', sa.Column('output_key', sa.String(), nullable=True), schema='agent_forge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'output_key', schema='agent_forge')
    op.drop_column('agents', 'output_schema', schema='agent_forge')
    # ### end Alembic commands ###
