"""add agent and skill collaborators

Revision ID: 60a63e1accd8
Revises: 1c434e403b77
Create Date: 2026-07-17 15:47:48.886098

"""
from alembic import op
import sqlalchemy as sa


revision = '60a63e1accd8'
down_revision = '1c434e403b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_collaborators',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_forge.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'user_email'),
    schema='agent_forge'
    )
    op.create_table('skill_collaborators',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['agent_forge.skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'user_email'),
    schema='agent_forge'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_collaborators', schema='agent_forge')
    op.drop_table('agent_collaborators', schema='agent_forge')
    # ### end Alembic commands ###
