"""add transcript column to invocation_log

Revision ID: 6d5d5f21bae4
Revises: 9e65c5d7c0cd
Create Date: 2026-07-06 14:46:42.353714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6d5d5f21bae4'
down_revision = '9e65c5d7c0cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invocation_log', sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='agent_forge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invocation_log', 'transcript', schema='agent_forge')
    # ### end Alembic commands ###
