"""init agent_forge schema

Revision ID: 9e65c5d7c0cd
Revises: 
Create Date: 2026-07-06 11:32:07.281520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9e65c5d7c0cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_instruction', sa.Text(), nullable=False),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='agents_status_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_forge'
    )
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False, schema='agent_forge')
    op.create_table('config_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'publish', 'archive', 'delete')", name='config_audit_log_action_check'),
    sa.CheckConstraint("entity_type IN ('agent', 'tool', 'skill')", name='config_audit_log_entity_type_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_forge'
    )
    op.create_index('ix_config_audit_log_entity_type_entity_id_created_at', 'config_audit_log', ['entity_type', 'entity_id', 'created_at'], unique=False, schema='agent_forge')
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False),
    sa.Column('few_shot_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_forge'
    )
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tool_type IN ('http_tool', 'sql_tool', 'mcp_tool', 'retrieval_tool')", name='tools_tool_type_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_forge'
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('attach_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_forge.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['agent_forge.skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id'),
    schema='agent_forge'
    )
    op.create_index('ix_agent_skills_skill_id', 'agent_skills', ['skill_id'], unique=False, schema='agent_forge')
    op.create_table('agent_subagents',
    sa.Column('parent_agent_id', sa.UUID(), nullable=False),
    sa.Column('child_agent_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('parent_agent_id != child_agent_id', name='agent_subagents_no_self_ref'),
    sa.ForeignKeyConstraint(['child_agent_id'], ['agent_forge.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agent_forge.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_agent_id', 'child_agent_id'),
    schema='agent_forge'
    )
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_forge.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['agent_forge.tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id'),
    schema='agent_forge'
    )
    op.create_index('ix_agent_tools_tool_id', 'agent_tools', ['tool_id'], unique=False, schema='agent_forge')
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_forge.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='agent_versions_agent_id_version_key'),
    schema='agent_forge'
    )
    op.create_table('invocation_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_version', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('invoked_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'error', 'timeout')", name='invocation_log_status_check'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_forge.agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_forge'
    )
    op.create_index('ix_invocation_log_agent_id_created_at', 'invocation_log', ['agent_id', 'created_at'], unique=False, schema='agent_forge')
    op.create_index('ix_invocation_log_workspace_id_created_at', 'invocation_log', ['workspace_id', 'created_at'], unique=False, schema='agent_forge')
    op.create_table('tool_call_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invocation_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'error')", name='tool_call_log_status_check'),
    sa.ForeignKeyConstraint(['invocation_id'], ['agent_forge.invocation_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['agent_forge.tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_forge'
    )
    op.create_index('ix_tool_call_log_tool_id_created_at', 'tool_call_log', ['tool_id', 'created_at'], unique=False, schema='agent_forge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_call_log_tool_id_created_at', table_name='tool_call_log', schema='agent_forge')
    op.drop_table('tool_call_log', schema='agent_forge')
    op.drop_index('ix_invocation_log_workspace_id_created_at', table_name='invocation_log', schema='agent_forge')
    op.drop_index('ix_invocation_log_agent_id_created_at', table_name='invocation_log', schema='agent_forge')
    op.drop_table('invocation_log', schema='agent_forge')
    op.drop_table('agent_versions', schema='agent_forge')
    op.drop_index('ix_agent_tools_tool_id', table_name='agent_tools', schema='agent_forge')
    op.drop_table('agent_tools', schema='agent_forge')
    op.drop_table('agent_subagents', schema='agent_forge')
    op.drop_index('ix_agent_skills_skill_id', table_name='agent_skills', schema='agent_forge')
    op.drop_table('agent_skills', schema='agent_forge')
    op.drop_table('tools', schema='agent_forge')
    op.drop_table('skills', schema='agent_forge')
    op.drop_index('ix_config_audit_log_entity_type_entity_id_created_at', table_name='config_audit_log', schema='agent_forge')
    op.drop_table('config_audit_log', schema='agent_forge')
    op.drop_index('ix_agents_status', table_name='agents', schema='agent_forge')
    op.drop_table('agents', schema='agent_forge')
    # ### end Alembic commands ###
